
name: objc_archive
version: 0.0.1
language: objc
description: objc archive
public: true
tags:
  - objc
  - archive
inputs:
  - name: FLOW_ENABLE_FAILURE
    editable: true
    options:
      - TRUE
      - FALSE
outputs:
script_path: ./run.sh  
  
template: |  
  
  